name: CI

on:
  push:
    branches: ['**']
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom, curl, fileinfo, zip
          tools: composer:v2

      - name: Show versions
        run: |
          php -v
          composer -V
          node -v
          npm -v

      - name: Composer install (dev)
        env:
          COMPOSER_MEMORY_LIMIT: -1
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci || npm install --no-audit --no-fund

      - name: Build assets
        run: npm run build --if-present

      #  .env  APP_KEY  
      - name: Prepare .env (testing)
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      #  -   / -> /en;   -
      - name: Run PHPUnit (unit only)
        if: ${{ hashFiles('phpunit.xml*') != '' }}
        run: vendor/bin/phpunit --testsuite=Unit --testdox
