name: DEBUG Deploy connectivity

on:
  workflow_dispatch:
  push:
    branches: [dev-debug]   #    

jobs:
  debug:
    runs-on: self-hosted
    steps:
      - name: Show runner tools
        run: |
          set -x
          which rsync || true; rsync --version || true
          which ssh   || true; ssh -V || true

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: List loaded SSH keys
        run: ssh-add -l || true

      - name: Test SSH to TEST (very verbose)
        run: |
          set -euxo pipefail
          ssh -vvv -o BatchMode=yes -o StrictHostKeyChecking=no \
            "${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}" 'echo SSH_OK'

      - name: Rsync dry-run
        run: |
          set -euxo pipefail
          mkdir -p tmp-empty
          rsync -azvvn -e "ssh -o StrictHostKeyChecking=no" \
            tmp-empty/ "${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_PATH }}/"
