name: Deploy TEST
on: {push:{branches:[dev]}}
jobs: {dummy:{runs-on:ubuntu-latest, steps:[{run:'echo deploy test'}]}}

- name: Rsync to TEST
  run: |
    rsync -az --delete \
      --exclude ".git" \
      --exclude ".github" \
      --exclude "node_modules" \
      --exclude "vendor/bin" \
      --exclude "storage/" \
      --exclude ".env" \
      --exclude ".env.*" \
      ./ ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_PATH }}
