name: Deploy to TEST (192.168.1.15)

on:
  push:
    branches: [ dev ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    # если добавлял свою метку в раннере, раскомментируй строку ниже
    # labels: [ test ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom, curl, fileinfo, zip
      - name: Install composer deps (no-dev)
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
      - name: Build assets
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install --no-audit --no-fund
      - run: npm run build --if-present

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync to TEST
        run: |
          rsync -az --delete \
            --exclude ".git" --exclude "node_modules" --exclude "vendor/bin" \
            ./ ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }}:${{ secrets.TEST_PATH }}

      - name: Post-deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.TEST_USER }}@${{ secrets.TEST_HOST }} << 'EOF'
          cd ${{ secrets.TEST_PATH }}
          # ключ приложения (один раз, если пусто)
          if ! grep -q '^APP_KEY=' .env || [ -z "$(grep '^APP_KEY=' .env | cut -d= -f2)" ]; then
            php artisan key:generate
          fi
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link || true
          # права/контексты
          find storage -type d -exec chmod 775 {} \;
          find storage -type f -exec chmod 664 {} \;
          chmod -R ug+rw bootstrap/cache
          # SELinux (если включен)
          which chcon && chcon -R -t httpd_sys_rw_content_t storage bootstrap/cache || true
    
