name: Deploy to PROD (tsoy.eu)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, dom, curl, fileinfo, zip

      - name: Install Composer deps (no-dev)
        env:
          COMPOSER_MEMORY_LIMIT: -1
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node deps
        run: npm ci || npm install --no-audit --no-fund

      - name: Build assets
        run: npm run build --if-present

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # при желании можно завести SSH_PRIVATE_KEY_PROD и подставить его

      - name: Rsync to PROD
        run: |
          rsync -az --delete \
            --exclude ".git" --exclude ".github" \
            --exclude "node_modules" --exclude "vendor/bin" \
            --exclude "storage/" --exclude ".env" --exclude ".env.*" \
            ./ "${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:${{ secrets.PROD_PATH }}"

      - name: Post-deploy
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}" << 'EOF'
          set -e
          cd "${{ secrets.PROD_PATH }}"
          if [ ! -f .env ]; then
            echo "ERROR: .env not found on server"; exit 1
          fi
          if ! grep -q '^APP_KEY=' .env || [ -z "$(grep '^APP_KEY=' .env | cut -d= -f2)" ]; then
            php artisan key:generate
          fi
          php artisan optimize
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan storage:link || true
          find storage -type d -exec chmod 775 {} \;
          find storage -type f -exec chmod 664 {} \;
          chmod -R ug+rw bootstrap/cache
          command -v restorecon >/dev/null 2>&1 && restorecon -Rv storage bootstrap/cache || true
          EOF
